### ISSUE TITLE
Feature request: implement "undo +1" button

### ISSUE THREAD

**Issue by michal-kazmierczak** [netguru/props#18]
#### Problem
As a user when browsing list of props I can give a like to any prop by clicking "+1". When misclicked, I cannot undo this operation. 

#### Task
Implement "undo +1" button that is visible only in suitable situation and gives opportunity to cancel like. 

Make sure it's safe, don't forget about tests.

**Comment by sbrych** [comment]
Done in https://github.com/netguru/props/pull/61
